burden_and_pools:
  - !!python/tuple [5, 650]
  - !!python/tuple [20, 650]
  - !!python/tuple [100, 1550]
mode: "signal_implantation"
olga_model: "humanTRB"
n_repertoires: 800
n_sequences: 25000
n_threads: 80
noise_rate: 0.2
output_path: ""
seed: ""
signal_sequences_file: ""
signal_pgen_count_mapping_file: ""
phenotype_burden: ""
phenotype_pool_size: ""
allow_closer_phenotype_burden: True
store_intermediate_files: False
export_nt: False
background_sequences_path: "/path/to/concatenated_covid_repertoires.tsv"
usecase_name: "q1_fullseq"
super_path: "/path/to/q1_fullseq_data"
signal_file: 
  100: 
    run1: "/path/to/vdjdb_downloaded/cmv_23072024_part1.tsv"
    run2: "/path/to/vdjdb_downloaded/cmv_23072024_part2.tsv"
    run3: "/path/to/vdjdb_downloaded/cmv_23072024_part3.tsv"
  20: 
    run1: "/path/to/vdjdb_downloaded/influenza_a_23072024_part1.tsv"
    run2: "/path/to/vdjdb_downloaded/influenza_a_23072024_part2.tsv"
    run3: "/path/to/vdjdb_downloaded/influenza_a_23072024_part3.tsv"
  5: 
    run1: "/path/to/vdjdb_downloaded/ebv_23072024_part1.tsv"
    run2: "/path/to/vdjdb_downloaded/ebv_23072024_part2.tsv"
    run3: "/path/to/vdjdb_downloaded/ebv_23072024_part3.tsv"
signal_mapping_file:
  100: null
  20: "/path/to/signal_mapping_burden_20.tsv"
  5: "/path/to/signal_mapping_burden_5.tsv"
reps: ["run1", "run2", "run3"]